services:
  - type: web
    name: postgres-docker
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: adminpass
      - key: POSTGRES_DB
        value: mydb
    ports:
      - port: 5432
        protocol: tcp
